import { Config, Provide, Scope, ScopeEnum } from '@midwayjs/core'; import { InjectEntityModel } from '@midwayjs/typeorm'; import { createHmac, randomBytes, randomUUID, scryptSync, timingSafeEqual, createHash } from 'crypto'; import { Repository } from 'typeorm'; import { UserEntity } from '../entity/user_entity'; import { RefreshTokenEntity } from '../entity/refresh_token_entity';
@Provide() @Scope(ScopeEnum.Request, { allowDowngrade: true }) export class AuthService { @InjectEntityModel(UserEntity) users:Repository<UserEntity>; @InjectEntityModel(RefreshTokenEntity) refresh:Repository<RefreshTokenEntity>; @Config('auth') config:any;
 private secret(){return process.env.JWT_SECRET||'wu-dong-dev-secret';} private profile(u:UserEntity){return{id:String(u.id),phone:u.phone.replace(/^(\d{3})\d{4}(\d{4})$/,'$1****$2'),name:u.name,avatar:u.avatar,bio:u.bio,status:u.status};}
 private jwt(id:string){const h=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),p=Buffer.from(JSON.stringify({id,typ:'access',exp:Math.floor(Date.now()/1000)+7200,jti:randomUUID()})).toString('base64url');return h+'.'+p+'.'+createHmac('sha256',this.secret()).update(h+'.'+p).digest('base64url');}
 verify(token:string){try{const [h,p,s]=token.split('.');const sig=createHmac('sha256',this.secret()).update(h+'.'+p).digest('base64url');if(sig!==s)return null;const x=JSON.parse(Buffer.from(p,'base64url').toString());return x.exp>Date.now()/1000?String(x.id):null;}catch{return null;}}
 private hash(p:string){return scryptSync(p,this.secret(),32).toString('hex');}
 async login(phone:string,password?:string,sms?:string){if(!/^1\d{10}$/.test(phone))throw new Error('手机号格式不正确');let u=await this.users.findOneBy({phone});if(!u&&sms){u=await this.users.save(this.users.create({phone,name:phone,avatar:'',bio:'',passwordHash:'',status:'ENABLED'}));}if(!u||u.status!=='ENABLED'||(password&&u.passwordHash!==this.hash(password)))throw new Error('账号或密码错误');const rt=randomBytes(32).toString('base64url');await this.refresh.insert({userId:u.id,jti:rt,tokenHash:createHash('sha256').update(rt).digest('hex'),expiresAt:new Date(Date.now()+30*86400000)});return{token:this.jwt(String(u.id)),expire:7200,refreshToken:rt,user:this.profile(u)};}
 async register(phone:string,password:string,name:string){const u=await this.users.findOneBy({phone});if(u&&u.passwordHash)throw new Error('手机号已注册');const user=u||this.users.create({phone,avatar:'',bio:'',status:'ENABLED'});user.name=name||phone;user.passwordHash=this.hash(password);await this.users.save(user);return this.login(phone,password);}
 async me(id:string){const u=await this.users.findOneBy({id});if(!u||u.status!=='ENABLED')throw new Error('登录失效');return this.profile(u);} async logout(rt:string){if(rt)await this.refresh.update({jti:rt},{revokedAt:new Date()});}
}
